kind: Service
apiVersion: v1
metadata:
  name: klusterlet-addon-workmgr
  namespace: {{ .Namespace }}
  labels:
    app: work-manager
spec:
  type: ClusterIP
  ports:
  - name: app
    port: 443
    protocol: TCP
    targetPort: 4443
  selector:
    app: work-manager
